modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "netherite_ext"
version = "${version}"
displayName = "Netherite Extension"
authors = "IAFEnvoy"
description = '''
The high version port of Netherite Plus Mod
Add more netherite items into game.
'''
logoFile = "assets/netherite_ext/icon.png"

[[dependencies.netherite_ext]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherite_ext]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherite_ext]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
