modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "netherite_ext"
version = "${version}"
displayName = "Netherite Extension"
authors = "IAFEnvoy"
description = '''
The high version port of Netherite Plus Mod
Add more netherite items into game.
'''
logoFile = "logo.jpg"

[[dependencies.netherite_ext]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherite_ext]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherite_ext]]
modId = "architectury"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config="netherite_ext.mixins.json"